### PR TITLE
Licensing issues regarding Open Game Content

### PR DESCRIPTION
**Pull request by pepper-jk**
I actually was hoping to submit a different pull request today regarding my [alternative branch](https://github.com/pepper-jk/DnD-Latex-Charactersheet/tree/alternative). For this I wanted to host modified Character Sheets, which include Honor and/or Sanity as Abilities. This is why, I did some digging into the [Fan Content Policy](https://company.wizards.com/fancontentpolicy), the [Systems Reference Document](http://dnd.wizards.com/articles/features/systems-reference-document-srd) and the [Open Game License](http://www.opengamingfoundation.org/ogl.html).

After reading the license I think I found a mistake in my last pull request regarding the commands I wrote for the Character Level and Proficiency Bonus Calculation. It looks like I need to indicate said commands as **Open Game Content**, since they are based on the tables written in the [Systems Reference Document](http://dnd.wizards.com/articles/features/systems-reference-document-srd). Therefore in this pull request I added and linked the [Open Game License](http://www.opengamingfoundation.org/ogl.html) to conform to its requirements for using the tables.

Sadly this means that the Character Sheet may no longer be completely GPL conform. I have not yet figured out if the licenses are compatible. I hope that a co-existence is possible. I hope you do not mind this, however I completely understand if you want to keep the project strictly GPL only. I myself am a major FOSS enthusiast.

Another solution would be
- [x] to separate the commands in a different latex style sheet and import it if possible
- [ ] and if not it'll just fallback to basic user input, kind of similar to the Initiative that still has the manual user input fallback.
- [ ] This way the different licensed latex code would be separated more clearly.

I'm also thinking about other solutions for this, but I wanted to notify you of my mistake first.

If you dislike all above solutions and want to keep it completely GPL, I will gladly send you a pull request removing my changes, which have this issue. This should at least effect commit 17a94cfbbad6c6049bc10527b90acd6ca1b130e2.

Also please let me know if I messed up with my license research, as I might be mistaken.

### CODE REVIEW

**Comment by pagdot** [comment]
I've read the OGL and the Fan Content Policy and took a look at other D&D fan projects on Github. I'm no lawyer and licenses aren't that easy but according to the fan policy it should be no problem using this commands. The only missing thing on this repo is a note containing that this is unofficial.

Even if it doesn't match the criteria of the fan policy and the OGL, I think it was done for the best.

If you still want to remove said content I will do it, but I don't think it is necessary.

**Comment by pepper-jk** [comment]
Sorry for the long text. I don't think I can cut it down.

From what I understood so far, the basic rules of D&D were released under the OGL in the [Systems Reference Document](http://dnd.wizards.com/articles/features/systems-reference-document-srd). And since the rules I used for the commands are specified there, I fear that they also must be licensed under the OGL due to this paragraph:

> 2. The License: This License applies to any Open Game Content that contains a notice indicating that the Open Game Content may only be Used under and in terms of this License. You must affix such a notice to any Open Game Content that you Use. No terms may be added to or subtracted from this License except as described by the License itself. No other terms or conditions may be applied to any Open Game Content distributed using this License.

Further I don't think the GPL is allowed for Fan Content either, since the GPL allows commercial use and the Fan Content Agreement explicitly does not:

> One word: F-R-E-E. You can use Wizards’ IP (except for the restrictions listed in `#3`) to make Fan Content that you share with the community for free. Free means FREE:
> - You can’t require payments, surveys, downloads, subscriptions, or email registration to access your Fan Content;
> - You can’t sell or license your Fan Content to any third parties for any type of compensation; and
> - Your Fan Content must be free for others (including Wizards) to view, access, share, and use without paying you anything, obtaining your approval, or giving you credit.

However I do not think the Fan Content Agreement applies here anyway, since the core of my issue are the rules, which are again under OGL.

I also looked onto the website of the [Open Gaming Foundation](http://www.opengamingfoundation.org/), but the website was not updated since 2003 and there are no contacts regarding the OGL.

I was gonna send a [permission request](https://support.wizards.com/hc/en-us/requests/new) asking Wizards, if they think of the GPL as a compatible license to the OGL. But once I typed "Open Game License", I was given the following [link](https://support.wizards.com/hc/en-us/articles/360000902443?input_string=open+game+license+compatibility). Here they state:

> Using D&D fifth edition rules to publish your own content: Generally, we offer only two different programs that allow people to publish RPG products using our properties. The Dungeon Masters Guild program, and the Open Gaming License (OGL). At this time, we are not considering licenses to use our D&D rules that do not fit into these options. We are also not considering licenses to use any of our other non-D&D RPG rules at this time.

and

> D&D Fifth Edition SRD (with OGL): http://dnd.wizards.com/articles/features/systems-reference-document-srd. Unfortunately, Wizards of the Coast cannot provide assistance with, or legal interpretations for, questions related to our licenses. If you require further assistance with something beyond what can be found on our website, we recommend that you consult with a lawyer or other legal professional of your choosing qualified to interpret such documents.

Since Wizards also does not want to answer any questions, I will ask a friend who is studying law later this week. Also I might visit my universities legal assistance.

It's not so much that I am really worried about anything happening, I just want to do the licensing right. And it annoys me that no one seems to be responsible for the license, which is why we can not find a clear answers, to whether it is compatible or not. My goal is to find a clear answer and create a list of compatible and incompatible licenses.

I mean the easiest way would be to switch from GPL to OGL, but I'm not sure if I and especially if you would be comfortable with that.

**Comment by pepper-jk** [comment]
As you can see, I closed #3.

I'll try send you an update on my legal research tonight. But at the latest this weekend.

**Comment by pepper-jk** [comment]
Okay, first of I wanna apologize for the delay. I'm currently quite busy at work and in the evening usually exhausted. However this does not excuse my two weeks delay.

So now to the licensing issue at hand. I think i figured it out about a week ago with a friend of mine, who is studying law atm. I was half right with most my assumption so let's go through it one - hopefully last - time.

> From what I understood so far, the basic rules of D&D were released under the OGL in the Systems Reference Document. And since the rules I used for the commands are specified there, I fear that they also must be licensed under the OGL due to this paragraph:

Indeed §2 requires every distribution of the content released under the OGL to be again licensed under the OGL, in this case the D&D rules regarding the Experience Points, Level and calculation of the Proficiency Bonus.

### Regarding compatibility of the OGL and the GPLv3

First up, the GPLv3 is obviously not upward compatible with the OGL.

Next is the other way around, which is a bit tricky. I will need to read the exact words of the GPLv3 before making an indefinite conclusion.

However we found a section of the FAQ, which kind of answers this question [here](https://www.gnu.org/licenses/gpl-faq.html#MereAggregation).

> [...]
> Where's the line between two separate programs, and one program with two parts? [...]
> If the modules are included in the same executable file, they are definitely combined in one program. If modules are designed to run linked together in a shared address space, that almost surely means combining them into one program.
> [...]

To my knowledge all latex files, stylesheets and documents alike, are contained within the same address space during compilation. This would make same part of one "program" in the eyes of the GPLv3 and therefore a change of the license of the Open Game Content alone would violate the GPLs terms. Thus the core stylesheet could not longer stay under the GPL.
There is a solution. The LGPL does allow dynamic linking with any other license, which should be what we would be doing here. So we could switch to the LGPL to fix this issue.

Still that leaves the question about the .tex example file, provided in the repository. From my understanding of the OGL I figure it must be licensed under the OGL as well, since it would includes a stylesheet under the OGL.

We would need to add a notice to my stylesheet and the .tex file, which point to the open game license in this repository. We do not need to add the License to the pdf ourselves, since we do not distribute the rendered pdf, but the user of the stylesheets and the example tex file is obligated to do so. So I would suggest a legal notice like:
> This document was generated with the help of Open Game Content. If you receive this document outside the framework of personal use and you did not receive a copy of the Open Game License, persons distributing it are in violation of the Open Game License.

This is a lot to take in, so take your time. I understand that changing the license is nothing one does lightly. Let me know what you think.

p.s.

> and took a look at other D&D fan projects on Github.

I do not believe that a lot of people are aware of the OGL and since it is not really enforced in any way and Wizards obviously does not want to make enemies with fans over small projects, I think nobody ever bothered to look into this before. I might be wrong though.

**Comment by pagdot** [comment]
Sorry that i took that long to respond. The GPL and LGPL are licenses made especially for software. A latex document is not really a piece of software. It think both licenses aren't suited for this. I thought about an alternate license and I think I'll choose the MIT license because it is plain and simple.

**Comment by pepper-jk** [comment]
Okay, that makes things a little easier. However the OGL should also be not compatible with MIT. So would we would need to do is the same as the LGPL approach that I described before.

.tex - OGL
your .sty files - MIT
.sty with my changes - OGL

**Comment by pagdot** [comment]
Sorry for the delay. I think the .tex file could still be licensed under the MIT license because it doesn't contain content of the OGL.

**Comment by pepper-jk** [comment]
Well technically yes. But you still need to mark where the Open Game Content is used. So we need to add a comment to that.

I'm not sure if all the other fields need to be labeled as well, since they technically are Open Game Content too. That is why I suggested to just use the OGL for the .tex file too.

**Pull request closed without merging**
