### PR TITLE
Fixes and Additions

### PR DESCRIPTION
**Pull request by pepper-jk**
This pull request includes a variety of changes.

- The addition of a build script, which downloads the needed character sheet PDF files from the official wizards of the coast web page, if needed, renames them to fit the example latex file and generates the Character Sheet as a PDF.
  This was tested on ArchLinux, but should work with any Linux based system (or any other system providing bash or an equally capable shell).

- The addition of the official character details sheet, providing options like a backstory field.

- The proficiency bonus is now calculated by level (up to level 20) instead of having to set it manually. This gets rid of redundancy and also removes the possibility of user error.

- Initiative is now set to dexterity modifier by default, so you do not need to add it in the character sheet explicitly. I did not remove the option to set it manually though. I also added the option of providing the initiative bonus, which should be added to the modifier, in case someone picks up the Alert Feat. I think the bonus is a better solution since it gets added to the dex modifier automatically instead of having a hard coded value, which might again result in user error.

- I changed some spelling mistakes considering the word "dice", since "Hitdice" is a keyword.

- I also changed the \@DndBase@Hitdice@Count to actually be the counter for the hit dice and therefore be used as the modifier for \@DndBase@Hitdice@Desc.
  In the future we might want to allow lists of both to support multi class characters better. Since the character I use it for has two classes using d8 as hit dice I was to lazy to look up how to properly do this in latex style sheets.

- Changes to the white spaces. I removed any tabs or spaces at the end of a line. I also changed everything indented with spaces to tabs, since tabs were more commonly used throughout the documents.
  I personally like spaces better, but I thought I'd go with the original authors choice. Also it's a lot small of a commit this way.

Please let me know if there is anything you want me to change, before you merge this.

### CODE REVIEW

**Comment by pagdot** [comment]
Hi :)

Thank you for all the enhancements of the character sheet and support of the details sheet!

> - I also changed the @DndBase@Hitdice@Count to actually be the counter for the hit dice and therefore be used as the modifier for @DndBase@Hitdice@Desc.
In the future we might want to allow lists of both to support multi class characters better. Since the character I use it for has two classes using d8 as hit dice I was to lazy to look up how to properly do this in latex style sheets.

At the beginning I had it similar, but separated the actual count and the description to (kind of) support multiple hitdice. Although my approach isn't by far the most elegant solution it is a simple solution. Another solution would be to support an array-like input with multiple count and dice combinations.

> - Changes to the white spaces. I removed any tabs or spaces at the end of a line. I also changed everything indented with spaces to tabs, since tabs were more commonly used throughout the documents.

Hmm... I probably used different text editors with different tab-settings 🤦‍♂️.

> I personally like spaces better, but I thought I'd go with the original authors choice. Also it's a lot small of a commit this way.

I myself prefer spaces more but my text editor apparently didn't care....

**Comment by pepper-jk** [comment]
> At the beginning I had it similar, but separated the actual count and the description to (kind of) support multiple hitdice. Although my approach isn't by far the most elegant solution it is a simple solution. Another solution would be to support an array-like input with multiple count and dice combinations.

Okay, so you want me to revert the commit for this pull request?

Anything else you want me to change?

**Comment by pagdot** [comment]
> Okay, so you want me to revert the commit for this pull request?

Yes, please :)

> Anything else you want me to change?

No and thank you again for the great work 👍

**Comment by pepper-jk** [comment]
Done. I dropped the commit. Sorry for the late reaction, was learning for exams. But now I'm free.

**Comment by pepper-jk** [comment]
Oops. This is not an issue, but a pull request. I really need some sleep. :D

**Comment by pagdot** [comment]
Thanks again for all :)

**Pull request merged**
